prd:
  catalog_name: mlops_prd
  schema_name: cpablosr
acc:
  catalog_name: mlops_acc
  schema_name: cpablosr
dev:
  catalog_name: mlops_dev
  schema_name: cpablosr

parameters:
  learning_date: 0.001
  n_estimators: 1000
  max_depth: 3

dataset_name: hotel_reservations

id_column:
  Booking_ID
  
num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - required_car_parking_space
  - room_type_reserved
  - market_segment_type
  - repeated_guest

target_feature:
  booking_status
